### ISSUE TITLE
Space between posts

### ISSUE THREAD

**Issue by madhyamakist** [Windsooon/thanks-open-source#1]
The margins between the posts can be made better by:

1. Reducing the space occupied by the "heart" functionality.
2. Giving margin between posts in the mobile view.

Please find screenshots illustrating issue.
![screen shot 2017-11-24 at 12 10 56 pm](https://user-images.githubusercontent.com/1109442/33198394-e23e6cde-d110-11e7-894c-633a135e91d3.png)
![screen shot 2017-11-24 at 12 11 09 pm](https://user-images.githubusercontent.com/1109442/33198395-e282eeea-d110-11e7-902f-f5d1e3394fce.png)
![screen shot 2017-11-24 at 12 11 22 pm](https://user-images.githubusercontent.com/1109442/33198396-e2c5fce4-d110-11e7-8310-5a9e65befe5b.png)

**Comment by madhyamakist** [comment]
Let me know if you require help with the design/CSS, will be glad to help you out.

**Comment by Windsooon** [comment]
It will be great if you can write a patch for this issue

**Comment by Windsooon** [comment]
Thank you for your pr
