### ISSUE TITLE
Webpage font size too large on HIDPI screen.

### ISSUE THREAD

**Issue by ghost** [Windsooon/thanks-open-source#11]
## Checklist

- [*] I have verified that that issue exists against the `master` branch of Thank you open source.
- [*] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [*] I have included basic info like browser version, system version. (Occurs on Chrome Stable 74, Windows 10 1903. This is a 4k monitor of size 27 inch.)

## Steps to reproduce
Open the page.
## Expected behavior
Font size should be normal, at most 30 px for normal text to make it comfortable to read.
## Actual behavior
Font size is too large to read. See this ![screenshot of the webpage](https://user-images.githubusercontent.com/30282312/58674775-584a4d00-831f-11e9-9147-882fd7485e54.png).

**Comment by Windsooon** [comment]
Thank you. This bug had been fixed in [pull-request-12](https://github.com/thankyou-opensource/thankyou-open-source/pull/12).

**Comment by ghost** [comment]
> Thank you. This bug had been fixed in [pull-request-12](https://github.com/thankyou-opensource/thankyou-open-source/pull/12).

Thanks!
