### ISSUE TITLE
'Pick a repository' dropdown menu not working

### ISSUE THREAD

**Issue by bbusuioc** [Windsooon/thanks-open-source#3]
Steps to reproduce:
1. go to [https://www.thankyouopensource.com/](https://www.thankyouopensource.com/)
2. click on the 'Pick a repository' dropdown menu

Expected result:
- Show a list of repositories

What happens:
- nothing

Tested on Firefox 52.5.0 (Desktop) and on Firefox 59.0a1 (Android)

**Comment by Windsooon** [comment]
What I design is you have to type the repo name after clicking. Maybe I should change the placeholder text to search a repository?

**Comment by madhyamakist** [comment]
Yes, and IMO the cursor on hover is also misleading as to what that section does.

**Comment by bbusuioc** [comment]
Oh, I can see now it's working. For me, the arrow down was really confusing, as I expected something to happen immediately after clicking it.

Maybe changing the text to "Type in a repository..." or something similar and removing the arrow would do the trick.

Edit: Actually, just replacing the text should be fine. And yeah, the cursor on hover is also confusing.

**Comment by Windsooon** [comment]
Fixed
