### ISSUE TITLE
"Suggestions?" should link to GitHub issues

### ISSUE THREAD

**Issue by rugk** [Windsooon/thanks-open-source#4]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Thank you open source. (Well… website… but srsly the website is hopefully up-to-date)
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] ~I have included basic info like browser version, system version.~ 

## Suggestions

"Suggestions?" currently lets you write a mail. I think this is suboptimal, as this is a FLOSS project itself, so issues/suggestions should preferably be tracked online/transparently, so everyone can comment, improve, take these over, etc.
Of course you can also offer feedback via mail, but issue trackers should be preferred. Just my two cents…

**Comment by Windsooon** [comment]
I think so. Fixed on https://github.com/thankyou-opensource/thankyou-open-source/pull/5
