### ISSUE TITLE
Add thankyouopensource.com as website to Github repo description

### ISSUE THREAD

**Issue by Boldewyn** [Windsooon/thanks-open-source#6]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Thank you open source.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] I have included basic info like browser version, system version. (_Does not apply_)

## Steps to reproduce

Open https://github.com/thankyou-opensource/thankyou-open-source/

## Expected behavior

It would be cool, if the Github repo description contains the website URL `https://www.thankyouopensource.com/` to easily switch back to the website.

## Actual behavior

No link. :cry: 

Thank you for the idea and the implementation! This is really a good opportunity to express thanks.

**Comment by Windsooon** [comment]
Fix on #7
